### ISSUE TITLE
Support for other credential types

### ISSUE THREAD

**Issue by BjornerJF** [AdysTech/CredentialManager#10]
Will there be support for other credential types other than generic ? Nice if there could be an option for that. 
Reading a credential already saved in other than generic category, leads to a program crash.

**Comment by mvadu** [comment]
Sorry for late response. @BjornerJF what other kind of credentials you are referring to? The native API only supports reading Windows Credentials (for obvious security reasons, you don't want some random app reading your saved website passwords). 
The API can support Windows, which I am working on now.

![image](https://user-images.githubusercontent.com/8618235/41388369-a74bef60-6f59-11e8-8530-ea8ad47375be.png)

**Comment by jmarkman** [comment]
Sorry for the necropost on this issue, but I just wanted to ask about this sentence
> The native API only supports reading Windows Credentials (for obvious security reasons, you don't want some random app reading your saved website passwords).

Does this mean that the API **only** supports reading pre-existing Windows Credentials, or can the library create *new* Windows Credentials as well rather than just creating new Generic Credentials?

**Comment by esrahofstede** [comment]
See PR for a fix for the is issue #36
