### ISSUE TITLE
Question about GetCredentials() implementation

### ISSUE THREAD

**Issue by JohnDoe2193** [AdysTech/CredentialManager#18]
Following code exists in GetCredentials() implementation in CredentialManager.cs:

                        var ret1 = NativeCode.CredUIParseUserName(user, userBuilder, userBuilder.Capacity, domainBuilder, domainBuilder.Capacity);
                        lastError = Marshal.GetLastWin32Error();

                        //assuming invalid account name to be not meeting condition for CredUIParseUserName
                        //"The name must be in UPN or down-level format, or a certificate"
                        if (ret1 == NativeCode.CredentialUIReturnCodes.InvalidAccountName)
                            userBuilder.Append(user);
                        else if ((uint)ret1 > 0)
                            throw new Win32Exception(lastError, "CredUIParseUserName threw an error");

Can you explain why you execute **userBuilder.Append(user)** when **ret1** is **NativeCode.CredentialUIReturnCodes.InvalidAccountName**?

Essentially InvalidAccountName is treated as an "OK" outcome and I don't really understand the logic behind that.

**Comment by mvadu** [comment]
oh, its pretty simple..  [NativeCode.CredUIParseUserName](https://docs.microsoft.com/en-us/windows/desktop/api/wincred/nf-wincred-creduiparseusernamea
) function extracts the domain and user account name from a fully qualified user name. It expects `<DomainName>\<UserName>` or `<UserName>@<DNSDomainName>`, and throws `ERROR_INVALID_ACCOUNT_NAME` in case of an user name which does not have a domain qualified name. So I treat it as valid use case and use the entire username as stored.

**Comment by JohnDoe2193** [comment]
Thank you, makes sense now.
