### ISSUE TITLE
Additional initialization needed on Windows Server 2008 R2

### ISSUE THREAD

**Issue by JohnDoe2193** [AdysTech/CredentialManager#19]
File: **CredentialManager.cs**, 
function: **private static bool PromptForCredentials(string target, NativeCode.CredentialUIInfo credUI, ref bool save, out string user, out string password, out string domain)**

On Windows 10 and Windows Server 2016 this works fine the way it is now but on Windows Server 2008 R2 dialog to enter credentials never appears and following exception is thrown:

System.NullReferenceException: Object reference not set to an instance of an object.
   at AdysTech.CredentialManager.Credential..ctor(NetworkCredential credential)
   at AdysTech.CredentialManager.CredentialManager.SaveCredentials(String Target, NetworkCredential credential)

I found this SO post related to this issue: https://stackoverflow.com/questions/25885369/windows-api-function-creduipromptforwindowscredentials-also-returns-an-error-of

The SO post is for C++, for C# following needs to be added after credUI.cbSize = Marshal.SizeOf(credUI); 

            credUI.hwndParent = IntPtr.Zero;
            credUI.pszMessageText = "User Credentials";
            credUI.pszCaptionText = "Enter User Credentials";
            credUI.hbmBanner = IntPtr.Zero;

**Comment by JohnDoe2193** [comment]
More specifically, I found that only this initialization is required:

`credUI.pszMessageText = "User Credentials";`

but it doesn't hurt to initialize the rest.

**Comment by mvadu** [comment]
Sure, I will do it in next minor version. Since you have done this much analysis already, do you want to submit a PR with this fix?

**Comment by JohnDoe2193** [comment]
I didn't clone it via GitHub, so can't submit a PR. FYI: this affects both Windows 7 and Windows 2008 R2

**Comment by mvadu** [comment]
Thank you.. I must have an old Windows 7 VM, so should be able to test. I will take it up this weekend.
________________________________

**Comment by mvadu** [comment]
Hi @JohnDoe2193 current code already has these initialization with an override `public static NetworkCredential PromptForCredentials(string Target, ref bool save, string Message, string Caption)`

```
credUI.pszMessageText = Message;
credUI.pszCaptionText = Caption;
```

Can you please try if this method works on Win2008R2?
