### ISSUE TITLE
CredUnPackAuthenticationBuffer() never parses domain name

### ISSUE THREAD

**Issue by JohnDoe2193** [AdysTech/CredentialManager#20]
CredUnPackAuthenticationBuffer() never parses domain name

In file **CredentialManager.cs**, function **private static bool PromptForCredentials(string target, NativeCode.CredentialUIInfo credUI, ref bool save, out string user, out string password, out string domain)** makes following call:

```
if (NativeCode.CredUnPackAuthenticationBuffer(0, outCredBuffer, outCredSize, usernameBuf, ref maxUserName, domainBuf, ref maxDomain, passwordBuf, ref maxPassword))
{
....
}
```

No matter what I enter (user4444@domain.org or domain1\user444) that call always fails to return anything in **domainbuf**

How can this be explained?

**Comment by mvadu** [comment]
Are you testing it on Windows server 2008? We have tests (IntegrationTest, TestGetCredentials). One of them is run as part of the CI build. So its working in recent Windows versions.

**Comment by JohnDoe2193** [comment]
No I am testing on Windows 10. And all tests complete, sure, but TestPromptForCredentials() outputs following to Output window:

```
Domain null
InvalidParameter
```
If you trace where this happens in the debugger you will see what I mean.

**Comment by mvadu** [comment]
Oh, I think I know what you are referring to. The idea of this library was to capture credentials from user and pass it in Basic header. Basic header by definition does not have a "domain", though you can send the domain in the `user@org` or `org\user` format. 

I use [CredUIPromptForWindowsCredentialsW ](https://docs.microsoft.com/en-us/windows/desktop/api/wincred/nf-wincred-creduipromptforwindowscredentialsw) to ask for the credentials. This supports only generic credentials or secure credentials (i.e. in a secure desktop).  [CredUnPackAuthenticationBuffer](https://docs.microsoft.com/en-us/windows/desktop/api/wincred/nf-wincred-credunpackauthenticationbufferw) is then used to convert the buffer to a managed strings. The documentation is still TBD for domain part, so I am not sure if it is even designed to split the domain from user name.

Hence in my code if the domain is null I call [CredUIParseUserName](https://docs.microsoft.com/en-us/windows/desktop/api/wincred/nf-wincred-creduiparseusernamew) to  split the user name and domain. Note that `CredUIParseUserName` has its own criteria and it will not split `user@domain` but handled `domain\user`  !! 

```
 if (String.IsNullOrWhiteSpace(domain))
                    {
                        Debug.WriteLine("Domain null");
                        if (!ParseUserName(usernameBuf.ToString(), usernameBuf.Capacity, domainBuf.Capacity, out user, out domain))
                            user = usernameBuf.ToString();
                        password = passwordBuf.ToString();
                    }
```
