### ISSUE TITLE
CredentialManager.GetCredentials() failed

### ISSUE THREAD

**Issue by labkeeper** [AdysTech/CredentialManager#3]
When I want to retrieve credential CredentialManager.GetCredentials() throws an exception:
System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Nieprawidłowy element Win32 FileTime.
Nazwa parametru: fileTime
  Source=mscorlib
  ParamName=fileTime
  StackTrace:
       w System.DateTime.FromFileTimeUtc(Int64 fileTime)
       w System.DateTime.FromFileTime(Int64 fileTime)
       w AdysTech.CredentialManager.Credential..ctor(NativeCredential ncred)
       w AdysTech.CredentialManager.CriticalCredentialHandle.GetCredential()
       w AdysTech.CredentialManager.CredentialManager.GetCredentials(String Target)
       w WebDAVPOC.Program.Main(String[] args) w d:\Users\andrzejp\Documents\Visual Studio 2013\Projects\WebDAVPOC\WebDAVPOC\Program.cs:wiersz 20
       w System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       w System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       w Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       w System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by nguillermin** [comment]
I am getting a similar issue on windows 7, which is annoying because it works fine on my computer (Win 10).

![image](https://user-images.githubusercontent.com/2622768/31459501-5db3b2e0-ae91-11e7-94a1-8f33ede19dc4.png)

**Comment by mvadu** [comment]
@nguillermin Hi, thanks for reaching out. It was my bad, last fix did not update Nuget package version, which did not push the fix to Nuget. I have explicitly updated the version as a new PR and published it now. Can you please try updating the nugget package once again and confirm if its fixed?

**Comment by nguillermin** [comment]
@mvadu Sorry, I'd already copied the files from the latest by the time I got your message. I uninstalled and re-installed and it downloaded 1.2.0. Seems to be working.
