### ISSUE TITLE
Expose Credential directly

### ISSUE THREAD

**Issue by devedse** [AdysTech/CredentialManager#30]
Would it be possible to expose the Credentials directly?

They contain quite some information that doesn't fit inside the NetworkCredential class.

E.g.:
```
/// <summary>
        /// Enumerate the specified stored credentials in the Windows Credential store
        /// </summary>
        /// <param name="target">Name of the application or URL for which the credential is used</param>
        /// <returns>Return a <see cref="List{NetworkCredential}"/> if success, null if target not found, throw if failed to read stored credentials</returns>
        public static List<Credential> EnumerateCredentialsOriginal(string target = null)
        {
            IntPtr pCredentials = IntPtr.Zero;
            uint count = 0;

            var success = NativeCode.CredEnumerate(target, 0, out count, out pCredentials);

            if (!success)
            {
                var lastError = Marshal.GetLastWin32Error();
                if (lastError == (int)NativeCode.CredentialUIReturnCodes.NotFound)
                {
                    return null;
                }

                throw new Win32Exception(lastError,
                    string.Format("'CredEnumerate' call throw an error (Error code: {0})", lastError));
            }

            List<NetworkCredential> networkCredentials = new List<NetworkCredential>();
            Credential[] credentials;

            try
            {
                using (var criticalSection = new CriticalCredentialHandle(pCredentials))
                {
                    credentials = criticalSection.EnumerateCredentials(count);
                }
            }
            catch (Exception)
            {
                return null;
            }

            return credentials.ToList();
        }
```

**Comment by mvadu** [comment]
Sorry for leaving this issue open for so long.. Do you know what you are missing in `NetworkCredential` which you think should be exposed? Currently `Credential` is an `internal` class, and exposing it to be a public needs some justification.

**Comment by devedse** [comment]
Well I guess this all depends on the project at hand. But since this seems to be one of the only libraries that correctly implements a credentials manager within C# to me it would make sense to allow developers to access all properties that are exposed by the credential manager.

To be fully honest, I don't really remember where I needed this for 😜, but I believe it had something to do with determining which of the credentials with my email adress in it, was actually the right one. (Usename was all the same, but the website it was used for was different)

**Comment by glennst43** [comment]
This would also be useful for me. I need access to the "TargetName" parameter.
