### ISSUE TITLE
Support .NET Standard?

### ISSUE THREAD

**Issue by RussKie** [AdysTech/CredentialManager#31]
Hi there,
We use your package in [Git Extensions](https://github.com/gitextensions/gitextensions/), which we are currently porting to .NET Core and .NET Standard. CredentialManager is built against .NET 4.5 which is causing some frictions.

Are there any plans to migrate to .NET Standard?

Thanks

**Comment by mvadu** [comment]
I can certainly work on porting it to core/standards. Do you have any timeline in mind? So that I can prioritize it.

**Comment by RussKie** [comment]
Oh that'd be awesome!
I've done a very quick and dirty port to .NET Standard 2.0, you can leverage it, if you wish - https://github.com/gitextensions/CredentialManager/commit/9f283b2c15eabeb120c22b471c135ef98e62d232

As far as our timelines - the sooner the better 😉 but I understand real life has a priority.
If you could get a new package available before December - it would be awesome.

Thanks again.

**Comment by mvadu** [comment]
Hi @RussKie since the issue you referred talks about .Net Core 3.0, should I target for 3.0 as well? I am having little bit of an issue with VS 2019 supporting core 3.0.

**Comment by RussKie** [comment]
Either .NET Core 3.0+ or .NET Standard 2.0+ work for our case, so whichever is easier for you.


> I am having little bit of an issue with VS 2019 supporting core 3.0.

What kind of issue?

**Comment by mvadu** [comment]
> What kind of issue?

I almost forgot I am talking to a Microsoft Dev, who can actually help me to resolve my issue :)
On command prompt i can see I have 3.0 SDK on my dev box, but VS 2019 does not show the standard 3.0 as an option, and manually editing .csproj to `<TargetFramework>netstandard3.0</TargetFramework>` results in an error.

```
NETSDK1045	The current .NET SDK does not support targeting .NET Standard 3.0.  Either target .NET Standard 2.1 or lower, or use a version of the .NET SDK that supports .NET Standard 3.0.	
```


```
c:\>dotnet --list-sdks
1.0.0-rc4-004771 [C:\Program Files\dotnet\sdk]
1.0.0 [C:\Program Files\dotnet\sdk]
1.0.4 [C:\Program Files\dotnet\sdk]
2.0.2 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
3.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by RussKie** [comment]
> <TargetFramework>netstandard3.0</TargetFramework>

We don't yet have netstandard3.0 :) 
This should be `netcoreapp3.0`:
```
<TargetFrameworks>netcoreapp3.0</TargetFrameworks>
// or
<TargetFrameworks>netstandard2.0</TargetFrameworks> // or 2.1
```

**Comment by mvadu** [comment]
ah.. i was ahead of time!! `<TargetFramework>netstandard2.1</TargetFramework>` worked.. thank you for helping me out.
