### ISSUE TITLE
CredentialManager.GetCredentials() throws System.ArgumentOutOfRangeException with "Not a valid Win32 FileTime"

### ISSUE THREAD

**Issue by andreasgrosche** [AdysTech/CredentialManager#32]
Using commit 9978cb6054a7ee065c08149e3e0d2300a1f0c660, this code
```
var credential = CredentialManager.GetCredentials("Target");
```
can throw a  ``System.ArgumentOutOfRangeException`` with "Not a valid Win32 FileTime".

The exception is thrown in [Credentials.cs at line 43](https://github.com/AdysTech/CredentialManager/blob/9978cb6054a7ee065c08149e3e0d2300a1f0c660/AdysTech.CredentialManager/Credential.cs#L43).

Solution:
Change the typecast of the right operand of the bitwise or-operator from ``ulong`` to ``uint``:
from
```
LastWritten = DateTime.FromFileTime((long)((ulong)ncred.LastWritten.dwHighDateTime << 32 | (ulong)ncred.LastWritten.dwLowDateTime));
```
to
```
LastWritten = DateTime.FromFileTime((long)((ulong)ncred.LastWritten.dwHighDateTime << 32 | (uint)ncred.LastWritten.dwLowDateTime));
```

Rationale: The typecast to ulong extends the sign bit. For negative values, the upper 32 bits are set to 1.

**Comment by mvadu** [comment]
fixed with #33
