### ISSUE TITLE
Master build is failing: Invalid API key

### ISSUE THREAD

**Issue by cwchapma** [AdysTech/CredentialManager#37]
The master build is failing to publish Nuget packages:

```
Error publishing package. NuGet server returned 403: The specified API key is invalid, has expired, or does not have permission to access the specified package.
````

https://ci.appveyor.com/project/AdysTech/credentialmanager

**Comment by mvadu** [comment]
Nuget is pushing for keys with lower access than previous all access keys. I have updated it in the Nuget side, and slowly updating my repos. Please stay with me for a day or two.

**Comment by cwchapma** [comment]
Good morning, @mvadu, Any progress on this?
