### ISSUE TITLE
Password is exposed in the process memory after saving in the Windows credentials storage

### ISSUE THREAD

**Issue by Eugenii10** [AdysTech/CredentialManager#39]
```c#
bool save = false;
NetworkCredential nc = new NetworkCredential();
nc.UserName = inputWindow.userTextBox.Text;
nc.SecurePassword = authSecureString;
AdysTech.CredentialManager.CredentialManager.SaveCredentials(assemblyName, nc);
nc = null;
```
Hello.
After `SaveCredentials(...)` is called, I can find an exposed password in the process memory with Cheat Engine 7.0. Before that moment I can't find the password with Cheat Engine, until I request the `NetworkCredential.Password` property's value.
The `authSecureString` is an instance of the `System.Security.SecureString` class.
There is the same situation with the "CredentialManagement" by iLya Lozovyy.

**Comment by mvadu** [comment]
There was a memory leak in the `SaveCredentials`. I am in the process of major rework of the library (v2.0) which is fixing it. Would you be able to retest this in a week time after I publish the new version to nuget. I am targeting to complete it over this weekend.

**Comment by Eugenii10** [comment]
Thanks!
> Would you be able to retest this in a week time after I publish the new version to nuget.

Ok. I will wait for the new version.
