### ISSUE TITLE
Getting Multiple targets

### ISSUE THREAD

**Issue by gnanamu** [AdysTech/CredentialManager#47]
Hi,

In my application i need to store multiple credentials. Targets will be different like below.
Target "My App:user=Gnana", username=Gnana
Target "My App:user=Jason", username=Jason
Target "My App:user=Ryan", username=Ryan
there is no problem in saving these values. problem is in retrieving the entries. Target name is dynamic based on the username. When i call EnumerateCredentials() without target i get list of all NetworkCredential stored in my machine. From that no way i can filter only the credentials that is specific to my app say target starts with 'My App'. 
Since EnumerateCredentials() returns list of NetworkCredential i cannot able to find the target on this. 
If i can able to directly enumerate ICredential then it would have satisfied my requirement. 
Another way we can do it?

Thanks
Gnana

**Comment by mvadu** [comment]
#46 is trying to address this issue. But its not implemented properly. I am in the middle of updating few other minor things. Most likely i will add what 46 suggested, and publish a new version. That should address your issue as well.
