### ISSUE TITLE
Delete Generic Certificate and Domain Password type credentials

### ISSUE THREAD

**Issue by AngeloA1983** [AdysTech/CredentialManager#56]
Dear all, I am having as per the above object:

I am able to use **CredentialManager.RemoveCredentials()** method to remove **Type: Generic** credentials.

But I cannot remove **Generic Certificate** and **Domain Password** credential types. I am new to c#, am I missing something?

Thanks in advance

Angelo
![image](https://user-images.githubusercontent.com/74248916/98678504-f50b7980-235e-11eb-9280-8ebe32fe34ab.png)

**Comment by mvadu** [comment]
I am little busy with usual life demands at the moment. Can I look at it in few days and get back?

**Comment by AngeloA1983** [comment]
Yes please, I will be waiting for your reply.

Thanks in advance.

Angelo

**Comment by mvadu** [comment]
@AngeloA1983 I tried to recreate your issue, and I am not able to recreate. Please look at #57 specifically the last test case added. See if you can recreate your issue with that code. specifically when you say "But I cannot remove Generic Certificate and Domain Password credential types" are you getting any exceptions?

**Comment by AngeloA1983** [comment]
Ok, here a few more details:

Here is my situation:

**E:\Users\airoldia1>cmdkey /list

Currently stored credentials:

    Target: Domain:target=danbttest1.danieli.it
    Type: Domain Password
    User: cosmo\airoldia1
    Saved for this logon only

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@8.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@4.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@1.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=OneDrive Cached Credential Business - Business1
    Type: Generic
    User: 3e47136a-2382-43d3-98e7-fa3646a91bfe
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@3.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@6.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@2.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@5.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@7.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=MicrosoftOffice16_Data:ADAL:3e47136a-2382-43d3-98e7-fa3646a91bfe@@@9.000000
    Type: Generic
    Local machine persistence

    Target: LegacyGeneric:target=Microsoft_OC1:uri=airoldia1@danieli.it:certificate:OCS:1
    Type: Generic Certificate
    User: <Certificate>**

First and last set of credentials create the issue:

Here is my full C# code:

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Management.Automation;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;
using AdysTech.CredentialManager;
using Microsoft.VisualBasic.CompilerServices;
using System.Net;


namespace ClearCredential_Manager
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }



        private void comboBox1_SelectedIndexChanged(object sender, EventArgs e)
        {

            int selectedIndex = this.comboBox1.SelectedIndex;
            Object selectedItem = selectedIndex.ToString();

            if (selectedItem.ToString() == "0")

            {

                var credentials = CredentialManager.EnumerateICredentials();
                this.comboBox1.BackColor = Color.LightGray;

                if (credentials != null)
                {
                    this.listBox1.Items.Clear();
                    this.listBox1.BackColor = Color.LightGreen;
                    credentials.ForEach(num => this.listBox1.Items.Add(num.TargetName));
          
                    if (this.listBox1.Items.Count == 0)
                    {
                        this.listBox1.BackColor = Color.Red;
                        this.listBox1.Items.Add("No stored credentials found to be removed!");
                    }
                    credentials = null;

                }

                else
                {
                    this.listBox1.Items.Clear();
                    this.listBox1.BackColor = Color.Red;
                    this.listBox1.Items.Add("No stored credentials found to be removed!");
                }


            }

            if (selectedItem.ToString() == "1")

            {

                this.comboBox1.BackColor = Color.LightGray;
                this.listBox1.Items.Clear();
                var credentials = CredentialManager.EnumerateICredentials();

                if (credentials != null)
                {

                    credentials.ForEach(num => { if (!num.TargetName.Contains("certificate")) CredentialManager.RemoveCredentials(num.TargetName); });

                    if (this.listBox1.Items.Count == 0)
                    {
                        this.listBox1.BackColor = Color.Red;
                        this.listBox1.Items.Add("No stored credentials found to be removed!");
                    }
                    else
                    {
                        this.listBox1.BackColor = Color.LightGreen;
                        this.listBox1.Items.Add("All stored credentials credentials successfully removed!");
                        credentials = null;
                    }
                }


                else
                {
                    this.listBox1.Items.Clear();
                    this.listBox1.BackColor = Color.Red;
                    this.listBox1.Items.Add("No stored credentials found to be removed!");
                }


            }




        }

       
    }

}


![image](https://user-images.githubusercontent.com/74248916/99947460-4e6ca300-2d78-11eb-958b-a9c816ec45cc.png)

![image](https://user-images.githubusercontent.com/74248916/99947540-6d6b3500-2d78-11eb-8fcb-0b51d2dbe632.png)

![image](https://user-images.githubusercontent.com/74248916/99947580-7b20ba80-2d78-11eb-9a6f-3a730fc1dadc.png)

Since the domain password credential is the first one, the code breaks immediately. If I remove it manually the code deletes all generic credentials leaving only this:

Currently stored credentials:

    Target: LegacyGeneric:target=Microsoft_OC1:uri=airoldia1@danieli.it:certificate:OCS:1
    Type: Generic Certificate
    User: <Certificate>

Hope this helps.

**Comment by AngeloA1983** [comment]
Hi, did you get my last reply? I still cannot figure how to make it work…
Thanks

[cid:image001.png@01D6D214.42420490]

**Comment by mvadu** [comment]
@AngeloA1983 sorry for the delay in responding. Thank you for providing this additional information. I am working on reproducing this error. Unfortunately without a smartcard, I am not able to add a certificate credentials to the vault. I should be able to figure out the `Type: Domain Password` piece. More to come.

**Comment by mvadu** [comment]
@AngeloA1983 I have tried deleting the windows credential type, and it was working just fine. So far I haven't been able to recreate your issue, but I did found an issue along, and fixed it in the latest version. Can you pull the latest nuget package and try your scenario again?

**Comment by AngeloA1983** [comment]
Very sorry, It's been my fault the whole time. I was giving to RemoveCredentials method only the targetname string and didn't realize i had to specify credentialtype As well, that it was by default generic.

Like I said, i still Have a Long way to go with c#.

Sorry for making you waste  a lot of time...
________________________________

**Comment by mvadu** [comment]
@AngeloA1983 glad to know :) But your issue was still valuable. Because of this I found out that `RemoveCredential` is not exposed on `ICredential` interface, and type was not set properly (#59). So I was able to fix a bug and enhance the library. Now when you enumerate, you can just call the Remove directly (e.g. `credentials.ForEach(x => { if (x.Type == CredentialType.Windows) Assert.IsTrue(x.RemoveCredential(),"RemoveCredentials returned false"); });)`) without having to worry about the type parameter.

**Comment by AngeloA1983** [comment]
Thanks a lot for supporting me anyway 😊 Really appreciate the help you gave me the whole time
