### ISSUE TITLE
CredWrite failed with the error code 87.

### ISSUE THREAD

**Issue by prem16** [AdysTech/CredentialManager#6]
Hi, Sir  I am Prem Murmu, i wrote the main class as mentioned in readme.
This is..

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace webcredential3
{
    class mainclasscredential
    {
        public static void Main(string[] args)
        {

         //CredentialManagerTest obj=new CredentialManagerTest();

            bool save = false;
            var cred = CredentialManager.PromptForCredentials("Some Webservice", ref save, "Please provide credentials", "Credentials for service");

            var cred2 = new NetworkCredential("TestUser", "Pwd");
            CredentialManager.SaveCredentials("TestSystem", cred);
            var cred1 = CredentialManager.GetCredentials("TestSystem");

        }
    }
}
 but when i run this i am getting an error and unable to fix it.
" CredWrite failed with the error code 87."
this pointing  to the method ->  CredentialManager.SaveCredentials("TestSystem", cred);
but unable to understand..

**Comment by mvadu** [comment]
What is the type of the project? If you have setup the project as a console project, then you need to use the `PromptForCredentialsConsole` instead of `PromptForCredentials`. The later is for the UI based projects.

**Comment by mvadu** [comment]
Closing due to lack of more information.
