### ISSUE TITLE
CRED_MAX_CREDENTIAL_BLOB_SIZE  is now (5*512)

### ISSUE THREAD

**Issue by ldattilo** [AdysTech/CredentialManager#65]
### Expected Behavior
SaveCredential can save large tokens.  This works if calling the Windows API directly.

### Actual Behavior
Credential.cs is forcing credentials to be less than 512 bytes.
`if (ncred.CredentialBlobSize > 512)`

The Windows 10 SDKs header file, wincred.h sets the CRED_MAX_CREDENTIAL_BLOB_SIZE to 5*512.  This allows much bigger passwords such as tokens over 2k to be stored.

### Steps to reproduce
```    [TestMethod, TestCategory("LongPassword")]
     public void TestSaveLongPassword()
     {
         string longPwd = string.Empty.PadRight(1080, '1');
         try
         {
                var cred = new NetworkCredential("AdysTech.CredentialManager.LongPassword", longPwd);
                Assert.IsNotNull(CredentialManager.SaveCredentials("TestSystem", cred), "SaveCredential failed");
         }
         catch (Exception e)
         {
             Assert.Fail("Unexpected exception of type {0} caught: {1}",
             e.GetType(), e.Message);
             return;
         }
```

**Comment by mvadu** [comment]
@ldattilo even today the [official documentation for CREDENTIAL structure ](https://docs.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentiala) mentions 512 byte length. Is this specific to Windows 10 alone?

```
CredentialBlobSize

The size, in bytes, of the CredentialBlob member. This member cannot be larger than CRED_MAX_CREDENTIAL_BLOB_SIZE (512) bytes.
```

**Comment by ldattilo** [comment]
BTW, the specific use case is OAUTH and JWT tokens which exceed 512 bytes. 

@mvadu , RE: 
> even today the [official documentation for CREDENTIAL structure ](https://docs.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentiala) mentions 512 byte length. 

Yes, I noticed this as well. I haven't checked the older SDKs (pre-Windows 10) to see when this changed.

>Is this specific to Windows 10 alone?

I'm not sure when it changed.  I tested without the guard on both Windows 10 desktop and Windows Server 2019 and it stored correctly.

**Comment by mvadu** [comment]
> I'm not sure when it changed. I tested without the guard on both Windows 10 desktop and Windows Server 2019 and it stored correctly. I've been poking around for a way to probe that API for the limit at run time.

Is there a way for you test on Windows Server 2016? That is the first server version based on Windows 10, and if it is 5*512 there, I think I am okay in updating this since most of the new code would be Win 10 on client side and 2016/2019+ in server side.

**Comment by ldattilo** [comment]
@mvadu , I wrote a unit test to verify the new size works on Windows Server 2016.  I can create a pull request for you if you grant me permissions. 

`
 
        [TestMethod, TestCategory("AppVeyor")]
        public void TestICredential_LongTokenShouldWork()
        {
            // Tokens can be large. 
            // The API header now says the max length is 5*512.
            const int tokenLength = 1040;
                       string test = "longPasswordTest";
            var net = new NetworkCredential(test, new String('1', tokenLength), test);
            ICredential cred = net.ToICredential();
            cred.TargetName = "TestSystem_LongPassword";
            Assert.IsNotNull(cred.SaveCredential(), "SaveCredential should handle passwords of token size");

            var cred1 = CredentialManager.GetCredentials("TestSystem_LongPassword");
            Assert.IsTrue(cred1.Password == net.Password, "Saved and retrieved password doesn't match");
        }`

**Comment by mvadu** [comment]
> @mvadu , I wrote a unit test to verify the new size works on Windows Server 2016. I can create a pull request for you if you grant me permissions.
> 
> `
> 
> ```
>     [TestMethod, TestCategory("AppVeyor")]
>     public void TestICredential_LongTokenShouldWork()
>     {
>         // Tokens can be large. 
>         // The API header now says the max length is 5*512.
>         const int tokenLength = 1040;
>                    string test = "longPasswordTest";
>         var net = new NetworkCredential(test, new String('1', tokenLength), test);
>         ICredential cred = net.ToICredential();
>         cred.TargetName = "TestSystem_LongPassword";
>         Assert.IsNotNull(cred.SaveCredential(), "SaveCredential should handle passwords of token size");
> 
>         var cred1 = CredentialManager.GetCredentials("TestSystem_LongPassword");
>         Assert.IsTrue(cred1.Password == net.Password, "Saved and retrieved password doesn't match");
>     }`
> ```

Thank you for checking this one @ldattilo. Please feel free to submit a PR (do a fork on your own profile, fix the code, add the unit test case you referenced above, update the version). I will gladly accept it.

**Comment by ldattilo** [comment]
Thanks @mvadu.  I created a PR  #66. I set the version to 2.5 in the csproj file. Please let me know if I've missed anything.
