### ISSUE TITLE
Doesn't support blank passwords

### ISSUE THREAD

**Issue by eddy-jones-dev** [AdysTech/CredentialManager#67]
When setting credentials directly in Windows, you are allowed to store credentials with a blank password. `Credential.SaveCredential` currently blocks this via the following:

`if (String.IsNullOrEmpty(this.CredentialBlob))
                throw new ArgumentNullException("CredentialBlob", "CredentialBlob can't be Null or Empty");`

Could this be removed, or made optional? Have tried removing it on a local version and everything else seems to work as intended.

**Comment by mvadu** [comment]
@eddy-jones-dev  let me test this out.. I was out for few days, just saw this one.

**Comment by mvadu** [comment]
@eddy-jones-dev  sorry, didn't put a comment here. I did push a code fix few days ago. You need to pass in an additional parameter to force blank password though.
